- hosts: localhost
  gather_facts: false
  vars_files:
  - roles/olm_disconnected/vars/main.yml
  - config.yml
  tasks:
  - name: Make temp directory
    tempfile:
      state: directory
      suffix: mig_olm_disconnected
    register: tmp_dir

  - include_tasks: roles/olm_disconnected/tasks/get_operator.yml
    loop: "{{ operators }}"
    loop_control:
      loop_var: operator
    vars:
      tmp_dir_path: "{{ tmp_dir.path }}"

  - name: Create catalog directory structure
    file:
      path: "{{ tmp_dir.path }}/manifests/{{ item.name }}"
      state: directory
    with_items: "{{ operators }}"

  - name: Extract operator metadata
    shell: "bsdtar --strip-components 1 -xf {{ item.name }}.tar.gz -C manifests/{{ item.name }}/"
    args:
      chdir: "{{ tmp_dir.path }}"
    with_items: "{{ operators }}"

  - name: Find CSVs
    find:
      paths: "{{ tmp_dir.path }}/manifests"
      patterns: '*clusterserviceversion*'
      recurse: true
    register: csvs

  - name: Copy CSVs
    copy:
      src: "{{ item.path }}"
      dest: ./
    with_items: "{{ csvs.files }}"
