- hosts: localhost
  gather_facts: false
  vars_files:
  - roles/olm_disconnected/vars/main.yml
  tasks:
  - name: Initialize operator list
    set_fact:
      redhat: []
      community: []
      certified: []

  - name: Download Red Hat package data
    uri:
      url: https://quay.io/cnr/api/v1/packages?namespace=redhat-operators
      return_content: yes
    register: packages

  - name: Generate Red Hat operator list
    set_fact:
      redhat: "{{ redhat + new_item }}"
    vars:
      new_item:
      - "{{ item.name.split('/')[-1] }}"
    with_items: "{{ packages.json }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Download community package data
    uri:
      url: https://quay.io/cnr/api/v1/packages?namespace=community-operators
      return_content: yes
    register: packages

  - name: Generate community operator list
    set_fact:
      community: "{{ community + new_item }}"
    vars:
      new_item:
      - "{{ item.name.split('/')[-1] }}"
    with_items: "{{ packages.json }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Download certified package data
    uri:
      url: https://quay.io/cnr/api/v1/packages?namespace=certified-operators
      return_content: yes
    register: packages

  - name: Generate certified operator list
    set_fact:
      certified: "{{ certified + new_item }}"
    vars:
      new_item:
      - "{{ item.name.split('/')[-1] }}"
    with_items: "{{ packages.json }}"
    loop_control:
      label: "{{ item.name }}"

  - name: Print operator list
    debug:
      msg:
      - redhat: "{{ redhat|sort }}"
      - community: "{{ community|sort }}"
      - certified: "{{ certified|sort }}"
